<?php
/**
 * @var LCB_RichSnippets_Block_Catalog_Breadcrumbs $this
 */
if (!$crumbs = $this->getCrumbs()) {
    return;
}
?>

<?php $crumbCount = count($crumbs) ?>
<?php $i = 1; ?>
<script type="application/ld+json">
{
    "@context": "http://schema.org",
    "@type": "BreadcrumbList",
    "itemListElement":
    [
    <?php foreach($crumbs as $_crumbInfo): ?>
        {
        "@type": "ListItem",
        "position": <?php echo $i ?>,
        "item":
            {
            "@id": "<?php echo $_crumbInfo['link'] ?>",
            "name": "<?php echo $this->escapeHtml($_crumbInfo['label']) ?>"
            }
        }<?php echo ($i != $crumbCount ? ',' : '') ?>
        <?php $i++ ?>
    <?php endforeach ?>
    ]
}
</script>
